language: R
sudo: false
cache: packages

r_packages:
 - devtools
 - covr
 
r_github_packages: 
 - EricMarcon/entropart

bioc_packages:
 - BiocStyle

after_success:
  - Rscript -e 'library(covr); codecov(type ="all")'
