# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' parallelCountNbd
#'
#' Create a 3-D array containing the number of neighbors around each point, per species
#'
#' @param r The vector of distances to take into account.
#' @param NbSpecies The number of species of the community.
#' @param x, y The coordinates of the points.
#' @param Type A vector containing the species of each point (as integer, i.e. the factor code).
#' @param Weight A vector containing the weights of points.
#' @export
parallelCountNbd <- function(r, NbSpecies, x, y, Type, Weight) {
    .Call(`_SpatDiv_parallelCountNbd`, r, NbSpecies, x, y, Type, Weight)
}

